services:
  db:
    container_name: auction_nest_db_dev
    image: postgres:13.4
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auction